### ISSUE TITLE
Introduce Window Proxy limitations from the start

### ISSUE THREAD

**Issue by camillelamy** [hemeryar/explainers#4]
You are introducing the policy with the following meaning:
"This page is not interested in communicating synchronously with other pages, unless they're same-origin and have the same policy"

I think it'd be good to add something along the lines of:
"and it will only accept WindowProxy asynchronous calls to a limited set of WindowProxy methods." to introduce the other main restriction of the policy right away. Then you can go into more details about what each part does and why it is useful for our goal of crossOriginIsolation with popups.

**Comment by hemeryar** [comment]
I introduce the full policy and then dive into the details over two paragraphs.
